"""initial migration

Revision ID: 2403450caf4c
Revises: 
Create Date: 2025-05-17 14:08:52.238323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2403450caf4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('group_external_id', sa.String(), nullable=False),
    sa.Column('data_local', sa.DATE(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('hora_local', sa.String(), nullable=True),
    sa.Column('tamanho', sa.String(), nullable=True),
    sa.Column('assunto', sa.String(), nullable=True),
    sa.Column('criado', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numeros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planilhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_upload', sa.DATE(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspeitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.CHAR(length=11), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('relevante', sa.Boolean(), nullable=True),
    sa.Column('last_update_date', sa.String(), nullable=True),
    sa.Column('last_update_cpf', sa.CHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.CHAR(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(), nullable=False),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('valor_antigo', sa.TEXT(), nullable=False),
    sa.Column('valor_novo', sa.TEXT(), nullable=False),
    sa.Column('data_alteracao', sa.TIMESTAMP(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('tipo_contato', sa.BOOLEAN(), nullable=False),
    sa.Column('numero_contato_id', sa.Integer(), nullable=False),
    sa.Column('numero_origem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_contato_id'], ['numeros.id'], ),
    sa.ForeignKeyConstraint(['numero_origem_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_numeros',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'numero_id')
    )
    op.create_table('interceptacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('planilha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.ForeignKeyConstraint(['planilha_id'], ['planilhas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interlocutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('versao', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('hora', sa.TIME(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ligacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ligacao_external_id', sa.String(), nullable=False),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('criador_ligacao', sa.String(), nullable=True),
    sa.Column('tipo_ligacao', sa.String(), nullable=True),
    sa.Column('criador_ip', sa.String(), nullable=True),
    sa.Column('criador_port', sa.String(), nullable=True),
    sa.Column('receptor', sa.String(), nullable=True),
    sa.Column('receptor_ip', sa.String(), nullable=True),
    sa.Column('receptor_port', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_external_id', sa.String(), nullable=True),
    sa.Column('internal_ticket_number', sa.String(), nullable=False),
    sa.Column('grupo_id', sa.String(), nullable=True),
    sa.Column('remetente', sa.String(), nullable=True),
    sa.Column('remetente_ip', sa.String(), nullable=True),
    sa.Column('remetente_dispositivo', sa.String(), nullable=True),
    sa.Column('tipo_mensagem', sa.String(), nullable=True),
    sa.Column('estilo_mensagem', sa.String(), nullable=True),
    sa.Column('tamanho_mensagem', sa.String(), nullable=True),
    sa.Column('remetente_porta', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numeros_suspeitos',
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.Column('suspeito_id', sa.Integer(), nullable=False),
    sa.Column('last_update_date', sa.String(), nullable=True),
    sa.Column('last_update_cpf', sa.CHAR(length=11), nullable=True),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.ForeignKeyConstraint(['suspeito_id'], ['suspeitos.id'], ),
    sa.PrimaryKeyConstraint('numero_id', 'suspeito_id')
    )
    op.create_table('interceptacoes_numeros',
    sa.Column('numero_id', sa.Integer(), nullable=False),
    sa.Column('interceptacao_id', sa.Integer(), nullable=False),
    sa.Column('is_alvo', sa.BOOLEAN(), nullable=False),
    sa.Column('relevante', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['interceptacao_id'], ['interceptacoes.id'], ),
    sa.ForeignKeyConstraint(['numero_id'], ['numeros.id'], ),
    sa.PrimaryKeyConstraint('numero_id', 'interceptacao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interceptacoes_numeros')
    op.drop_table('numeros_suspeitos')
    op.drop_table('mensagens')
    op.drop_table('ligacoes')
    op.drop_table('ips')
    op.drop_table('interlocutores')
    op.drop_table('interceptacoes')
    op.drop_table('grupos_numeros')
    op.drop_table('contatos')
    op.drop_table('audit_log')
    op.drop_table('usuarios')
    op.drop_table('suspeitos')
    op.drop_table('planilhas')
    op.drop_table('operacoes')
    op.drop_table('numeros')
    op.drop_table('grupos')
    # ### end Alembic commands ###
