"""Remover campo internal_ticket_number da tabela suspeitos

Revision ID: 4cfe2d52fccc
Revises: 62b3a0cb7dd6
Create Date: 2025-05-18 23:13:36.240978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfe2d52fccc'
down_revision = '62b3a0cb7dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspeitos', schema=None) as batch_op:
        batch_op.drop_column('internal_ticket_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suspeitos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_ticket_number', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
