"""add unique constraint to suspeitos_emails

Revision ID: 5c202db5cb40
Revises: 2403450caf4c
Create Date: 2025-05-17 17:09:31.038933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c202db5cb40'
down_revision = '2403450caf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspeitos_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suspeito_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('last_update_date', sa.String(), nullable=True),
    sa.Column('last_update_cpf', sa.CHAR(length=11), nullable=True),
    sa.ForeignKeyConstraint(['suspeito_id'], ['suspeitos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suspeito_id', 'email', name='unique_suspeito_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspeitos_emails')
    # ### end Alembic commands ###
