"""remove internalticket from number

Revision ID: 6965574723a8
Revises: 2403450caf4c
Create Date: 2025-05-17 18:53:26.626177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6965574723a8'
down_revision = '2403450caf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('numeros', schema=None) as batch_op:
        batch_op.drop_column('internal_ticket_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('numeros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_ticket_number', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
